CREATE TABLE GENERO (
  ID INT,
  GENERO VARCHAR(30),
  PRIMARY KEY (ID)
);

CREATE TABLE ENDERECO(
  ID INT,
  RUA VARCHAR2(30),
  BAIRRO VARCHAR2(30),
  CIDADE VARCHAR2(30),
  CEP VARCHAR2(8),
  PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE( 
  ID INT,
  NUMERO VARCHAR2(11) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE USUARIO(
  ID INT,
  NOME VARCHAR2(30),
  LOGIN VARCHAR2(30),
  PASSWORD VARCHAR2(60),
  ENDERECO_ID NUMBER,
  TELEFONE_ID NUMBER,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
  FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
  
);

CREATE TABLE AUTOR(
  ID INT,
  NOME VARCHAR2(30),
  ENDERECO_ID NUMBER,
  TELEFONE_ID NUMBER,
  PRIMARY KEY (ID),

  FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
  FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
)


CREATE TABLE EDITORA (
  ID INT,
  CNPJ_EDITORA VARCHAR2(11),
  NOME VARCHAR2(30),
  ENDERECO_ID NUMBER,
  TELEFONE_ID NUMBER,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
  FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
)

CREATE TABLE LIVRO(
  ID INT,
  TITULO VARCHAR2(30),
  EXEMPLAR NUMBER,
  USUARIO_ID NUMBER NOT NULL,
  AUTOR_ID NUMBER NOT NULL,
  EDITORA_ID NUMBER NOT NULL,
  GENERO_ID NUMBER NOT NULL,
  PRIMARY KEY (ID),

  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR (ID),
  FOREIGN KEY (EDITORA_ID) REFERENCES EDITORA (ID),
  FOREIGN KEY (GENERO_ID) REFERENCES GENERO (ID)
);

CREATE TABLE GENERO_LIVRO(
  ID INT,
  LIVRO_ID NUMBER NOT NULL,
  GENERO_ID NUMBER NOT NULL,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID),
  FOREIGN KEY (GENERO_ID) REFERENCES GENERO (ID)
)

CREATE TABLE GENERO_USUARIO(
  ID INT,
  USUARIO_ID NUMBER NOT NULL,
  GENERO_ID NUMBER NOT NULL,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (GENERO_ID) REFERENCES GENERO (ID)
)


CREATE TABLE EVENTO (
  ID ,
  USUARIO_ID NUMBER NOT NULL,
  LIVRO_ID NUMBER NOT NULL,
  TIPO VARCHAR2(10) CHECK( TIPO IN ('DEMANDAR','OFERECER') ),
  PRIMARY KEY (ID),
  
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID)
)

CREATE TABLE HISTORICO (
  ID INT,
  USUARIO_DESTINATARIO_ID NUMBER NOT NULL,
  USUARIO_REMETENTE_ID NUMBER NOT NULL,
  LIVRO_ID NUMBER NOT NULL,
  DATA_TROCA DATE NOT NULL,
  
  PRIMARY KEY (ID),
  
  FOREIGN KEY (USUARIO_DESTINATARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (USUARIO_REMETENTE_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID)
)

DROP DATABASE AUTOR;





