CREATE TABLE USUARIO(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  NOME VARCHAR2(30),
  LOGIN VARCHAR2(30),
  PASSWORD VARCHAR2(60),
  ENDERECO_ID NUMBER,
  TELEFONE_ID NUMBER,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
  FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
  
);

DROP TABLE USUARIO;

CREATE TABLE AUTOR(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  NOME VARCHAR2(30),
  ENDERECO_ID NUMBER,
  TELEFONE_ID NUMBER,
  PRIMARY KEY (ID),

  FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
  FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
)

DROP TABLE AUTOR CASCADE CONSTRAINTS;


CREATE TABLE EDITORA (
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  CNPJ_EDITORA VARCHAR2(11),
  NOME VARCHAR2(30),
  ENDERECO_ID NUMBER,
  TELEFONE_ID NUMBER,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID),
  FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (ID)
)

DROP TABLE EDITORA CASCADE CONSTRAINTS;


CREATE TABLE GENERO (
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  GENERO VARCHAR(30),
  PRIMARY KEY (ID)
);

CREATE TABLE ENDERECO(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  RUA VARCHAR2(30),
  BAIRRO VARCHAR2(30),
  CIDADE VARCHAR2(30),
  CEP VARCHAR2(8),
  PRIMARY KEY (ID)
);

CREATE TABLE TELEFONE( 
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  NUMERO VARCHAR2(11) NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE LIVRO(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  TITULO VARCHAR2(30),
  EXEMPLAR NUMBER,
  USUARIO_ID NUMBER NOT NULL,
  AUTOR_ID NUMBER NOT NULL,
  EDITORA_ID NUMBER NOT NULL,
  GENERO_ID NUMBER NOT NULL,
  PRIMARY KEY (ID),

  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (AUTOR_ID) REFERENCES AUTOR (ID),
  FOREIGN KEY (EDITORA_ID) REFERENCES EDITORA (ID),
  FOREIGN KEY (GENERO_ID) REFERENCES GENERO (ID)
);

DROP TABLE LIVRO CASCADE CONSTRAINTS;

CREATE TABLE GENERO_LIVRO(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  LIVRO_ID NUMBER NOT NULL,
  GENERO_ID NUMBER NOT NULL,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID),
  FOREIGN KEY (GENERO_ID) REFERENCES GENERO (ID)
)

DROP TABLE GENERO_LIVRO CASCADE CONSTRAINTS;


CREATE TABLE GENERO_USUARIO(
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  USUARIO_ID NUMBER NOT NULL,
  GENERO_ID NUMBER NOT NULL,
  PRIMARY KEY (ID),
  
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (GENERO_ID) REFERENCES GENERO (ID)
)

DROP TABLE GENERO_USUARIO CASCADE CONSTRAINTS;


CREATE TABLE EVENTO (
  ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
  USUARIO_ID NUMBER NOT NULL,
  LIVRO_ID NUMBER NOT NULL,
  TIPO  ENUM('OFERECER', 'DEMANDAR'),
  PRIMARY KEY (ID),
  
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID),
  FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID)
)




